@startuml

participant ApplyDiscountHandler
participant PersistSaleHandler
participant Sale
participant Customer
participant ICustomersRepository
participant ISalesRepository

ApplyDiscountHandler -> PersistSaleHandler : HandleAsync(context)
activate PersistSaleHandler

PersistSaleHandler -> Sale : CalculateTotal()
activate Sale
Sale --> PersistSaleHandler : saleAmount
deactivate Sale

alt context.SaleDiscount != null
    PersistSaleHandler -> PersistSaleHandler : saleAmount -= discount.Amount
end

PersistSaleHandler -> Customer : IncreaseTotalSales(saleAmount)

PersistSaleHandler -> ICustomersRepository : UpsertCustomerAsync(customer)
activate ICustomersRepository
ICustomersRepository --> PersistSaleHandler : customer
deactivate ICustomersRepository

PersistSaleHandler -> ISalesRepository : SaveSale(sale)
activate ISalesRepository
ISalesRepository --> PersistSaleHandler : sale
deactivate ISalesRepository

PersistSaleHandler -> PersistSaleHandler : base.HandleAsync(context)
note right : Delega al siguiente handler
deactivate PersistSaleHandler

@enduml
