@startuml ApplyDiscountHandler

class ApplyDiscountHandler {
    -_discountStrategyContext : DiscountStrategyContext
    +ApplyDiscountHandler(discountStrategyContext: DiscountStrategyContext)
    +HandleAsync(handlerContext: SaleHandlerContext) : Task
    -{static} SelectStrategy(handlerContext: SaleHandlerContext, total: decimal) : IDiscountStrategy?
}

@enduml
