@startuml CalculateDiscountResult

class CalculateDiscountResult <<record>> {
    +SubtotalBeforeDiscount : decimal
    +Discount : Discount?
    +{static} FromContext(context: SaleHandlerContext) : CalculateDiscountResult
}

@enduml
