@startuml CreateSaleHandler

class CreateSaleHandler {
    -_productsRepository : IProductsRepository
    +CreateSaleHandler(productsRepository: IProductsRepository)
    +HandleAsync(handlerContext: SaleHandlerContext) : Task
}

@enduml
