@startuml DiscountService

class DiscountService {
    -strategies : IEnumerable<IDiscountStrategy>
    +DiscountService(strategies: IEnumerable<IDiscountStrategy>)
    +GetDiscount(customer: Customer?, saleAmount: decimal) : Discount?
}

@enduml
