@startuml DiscountStrategyContext

class DiscountStrategyContext {
    -_strategy : IDiscountStrategy?
    +SetStrategy(strategy: IDiscountStrategy) : void
    +GetDiscount(saleAmount: decimal) : Discount?
}

@enduml
