@startuml EfProductsRepository

class EfProductsRepository {
    -dbContext : AppDbContext
    +EfProductsRepository(dbContext: AppDbContext)
    +ListAllProductsAsync() : Task<IReadOnlyList<Product>>
    +SearchProductByIdAsync(id: Guid) : Task<Product?>
}

@enduml
