@startuml ICustomersRepository

interface ICustomersRepository {
    +ListAllCustomersAsync() : Task<IReadOnlyList<Customer>>
    +ListAllCustomerIdsAsync() : Task<IReadOnlyList<Guid>>
    +SearchCustomerByNitAsync(nit: string) : Task<Customer?>
    +SearchCustomerByIdAsync(id: Guid) : Task<Customer?>
    +UpsertCustomerAsync(customer: Customer) : Task<Customer>
}

@enduml
