@startuml IProductsRepository

interface IProductsRepository {
    +ListAllProductsAsync() : Task<IReadOnlyList<Product>>
    +ListAllProductIdsAsync() : Task<IReadOnlyList<Guid>>
    +SearchProductByIdAsync(id: Guid) : Task<Product?>
}

@enduml
