@startuml PersistSaleHandler

class PersistSaleHandler {
    -_customersRepository : ICustomersRepository
    -_salesRepository : ISalesRepository
    +PersistSaleHandler(salesRepository: ISalesRepository, customersRepository: ICustomersRepository)
    +HandleAsync(context: SaleContext) : Task
}

@enduml
