@startuml SaleBaseHandler

abstract class SaleBaseHandler {
    -_next : SaleBaseHandler?
    +HandleAsync(handlerContext: SaleHandlerContext) : Task
    +SetNext(next: SaleBaseHandler) : SaleBaseHandler
}

@enduml
