@startuml SearchOrCreateCustomerHandler

class SearchOrCreateCustomerHandler {
    -_customersRepository : ICustomersRepository
    +SearchOrCreateCustomerHandler(customersRepository: ICustomersRepository)
    +HandleAsync(context: SaleContext) : Task
}

@enduml
