@startuml SearchOrCreateCustomerHandler

class SearchOrCreateCustomerHandler {
    -_customersRepository : ICustomersRepository
    +SearchOrCreateCustomerHandler(customersRepository: ICustomersRepository)
    +HandleAsync(handlerContext: SaleHandlerContext) : Task
}

@enduml
